language: node_js

services:
  - docker

before_install:
  - docker build -t kb . 
  - docker container run --name kbsite  -d kb
  - echo "$DH_PASSWD" | docker login -u "$DH_USER" --password-stdin
  - docker push "$DH_USER"/kb:lst
