language: node_js

services:
  - docker

before_install:
  - docker build -t kb:lst . 
  - docker container run --name kbsite  kb -d
  - echo "$DH_PASSWD" | docker login -u "$DH_USER" --password-stdin
  - docker push "$DH_USER"/kb:lst
